{
 "title": "Tablero de Control Principal - Huancabamba, Pasco",
 "description": "Lecturas de sensore IoT & alertas ante posibles sinietros ",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "zona",
    "query": "SELECT nombre AS __text, id AS __value FROM zonas"
   },
   {
    "name": "sensor",
    "query": "SELECT codigo AS __text, id AS __value FROM sensores WHERE zona_id IN ($zona)"
   }
  ]
 },
 "panels": [
  { "title": "📊 Telemetría en Tiempo Real", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Condiciones Climáticas en Tiempo Real - $zona",
   "type": "timeseries",
   "description": "Temperatura en grados Centigrados",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "fireprev",
     "rawSql": "SELECT\r\n  -- Agrupar por minuto (time_bucket de TimescaleDB es ideal aquí)\r\n  time_bucket('15 seconds', l.tiempo) AS \"time\",\r\n  AVG(l.temperatura) AS \"Temperatura\",\r\n  AVG(l.humedad) AS \"Humedad\"\r\nFROM lecturas l\r\nJOIN sensores s ON l.sensor_id = s.id\r\nWHERE\r\n  s.zona_id IN ($zona) AND\r\n  $__timeFilter(l.tiempo)\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Nivel de Humo en Tiempo Real - $zona",
   "type": "state-timeline",
   "description": "Concentración de Humo en PPM",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "fireprev",
     "rawSql": "SELECT\r\n  l.tiempo AS \"time\",\r\n  l.humo_ppm AS \"Humo\",\r\n  s.codigo AS \"Sensor\"\r\nFROM lecturas l\r\nJOIN sensores s ON l.sensor_id = s.id\r\nWHERE\r\n  s.zona_id IN ($zona) AND\r\n  $__timeFilter(l.tiempo)\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperatura Promedio por zona (Últimas 12 horas)  ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fireprev",
     "rawSql": "SELECT\r\n  z.nombre,\r\n  AVG(l.temperatura) as \"Temp Promedio\"\r\nFROM zonas z\r\nLEFT JOIN sensores s ON z.id = s.zona_id\r\nLEFT JOIN lecturas l ON s.id = l.sensor_id AND l.tiempo > NOW() - INTERVAL '12 hour'\r\nGROUP BY z.nombre\r\nORDER BY z.nombre ASC"
    }
   ]
  },
  { "title": "🚨 Alertas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Alertas Activas",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "fireprev",
     "rawSql": "SELECT\r\n  s.codigo AS \"SENSOR EN PELIGRO\",\r\n  z.nombre AS \"ZONA\",\r\n  l.temperatura AS \"TEMPERATURA\",\r\n  l.humedad AS \"HUMEDAD\",\r\n  l.humo_ppm AS \"NIVEL DE HUMO\",\r\n  l.tiempo AS \"FECHA - HORA\"\r\nFROM sensores s\r\nJOIN (\r\n    -- Subconsulta para obtener SOLO la última lectura de cada sensor\r\n    SELECT DISTINCT ON (sensor_id) sensor_id, temperatura , humedad, humo_ppm, tiempo\r\n    FROM lecturas\r\n    ORDER BY sensor_id, tiempo DESC\r\n) l ON s.id = l.sensor_id\r\nJOIN zonas z ON s.zona_id = z.id\r\nWHERE l.humo_ppm > 200  OR l.temperatura >= 35 AND l.humedad <= 30\r\nORDER BY l.humo_ppm DESC"
    }
   ]
  },
  {
   "title": "Historial de Alertas Generadas",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "fireprev",
     "rawSql": "SELECT\r\n  a.fecha AS \"Fecha - Hora\",\r\n  z.nombre AS \"Zona\",          \r\n  a.nivel AS \"Severidad\",\r\n  a.mensaje AS \"Detalle\",\r\n  s.codigo AS \"Sensor\"\r\nFROM alertas a\r\nJOIN sensores s ON a.sensor_id = s.id\r\nJOIN zonas z ON s.zona_id = z.id\r\nORDER BY a.fecha DESC\r\nLIMIT 10"
    }
   ]
  },
  { "title": "🌎 Mapa Geoespacial ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Distrito de Huancabamba, Oxapampa, Pasco",
   "type": "geomap",
   "description": "Perú",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "fireprev",
     "rawSql": "SELECT\r\n  s.latitud AS \"latitude\",\r\n  s.longitud AS \"longitude\",\r\n  l.temperatura AS \"temperatura\",\r\n  s.codigo AS \"sensor\"\r\nFROM sensores s\r\nJOIN (\r\n    SELECT DISTINCT ON (sensor_id) sensor_id, temperatura, tiempo\r\n    FROM lecturas\r\n    ORDER BY sensor_id, tiempo DESC\r\n) l ON s.id = l.sensor_id\r\nWHERE s.zona_id IN ($zona)"
    },
    {
     "dataset": "fireprev",
     "rawSql": "SELECT\r\n  latitud as lat,\r\n  longitud as lon,\r\n  60 as valor,\r\n  nombre as zona\r\nFROM zonas"
    }
   ]
  },
  { "title": "🔋 Salud de Infraestructura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Panel de Voltaje por Sensor - $zona",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fireprev",
     "rawSql": "SELECT\r\n  s.codigo AS \"Sensor\",\r\n  l.bateria_voltaje AS \"Voltaje\"\r\nFROM sensores s\r\nJOIN (\r\n    SELECT DISTINCT ON (sensor_id) sensor_id, bateria_voltaje\r\n    FROM lecturas\r\n    ORDER BY sensor_id, tiempo DESC\r\n) l ON s.id = l.sensor_id\r\nWHERE s.zona_id IN ($zona)\r\nORDER BY s.codigo ASC"
    }
   ]
  },
  {
   "title": "DeadSensor Check",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "dataset": "fireprev",
     "rawSql": "SELECT\r\n  s.codigo AS \"Sensor\",\r\n  to_char(NOW() - MAX(l.tiempo), 'HH24:MI:SS') as \"Tiempo Inactivo\"\r\nFROM sensores s\r\nJOIN lecturas l ON s.id = l.sensor_id\r\nGROUP BY s.codigo\r\nORDER BY 2 DESC"
    }
   ]
  }
 ]
}